### ISSUE TITLE
Process "Killed" using Python Vips8

### ISSUE THREAD

**Issue by HackerMD** [jcupitt/libvips#356]
I run a program that stitches images together to an overview using `merge() and join()`, performs some operations on the overview image, and writes the resulting image to disk in form of a zoomify pyramid using `dzsave()`.

Individual images exists on disk as PNG files with a size of 3.5 to 6MB per file.
The program works fine with small overviews, i.e. small number of images, but fails with a large number of images (about 10000 files).

The program get's killed with exitcode 137 (128+9) after the stitching as soon as a function is applied to the resulting `Vips.Image` object.

The error message is not very informative, it just says `Killed`.

This is the tail of the DEBUG log output:

```bash
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base self=<Image object at 0x7f1f0ea0dc80 (VipsImage at 0xe9e687e0)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0ea0dc80 (VipsImage at 0xe9e687e0)> to in1
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | in1 needs a <GType VipsImage (33612672)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0ea0dc80 (VipsImage at 0xe9e687e0)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0fcc2eb0 (VipsImage at 0x2ee0ca0)> to in2
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | in2 needs a <GType VipsImage (33612672)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0fcc2eb0 (VipsImage at 0x2ee0ca0)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning vertical to direction
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | direction needs a <GType VipsDirection (37071744)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning vertical
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base checking cache for op <__main__.VipsJoin object at 0x7f1f0ccaf3c0 (VipsJoin at 0xe9cc4e50)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base got op2 <__main__.VipsJoin object at 0x7f1f0ccaf3c0 (VipsJoin at 0xe9cc4e50)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base fetching required output args
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | read out <Image object at 0x7f1f0f1b88c0 (VipsImage at 0xe9fdaaf0)> from out
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base fetching optional output args
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | success
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | Image.__getattr__ percent
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base name=percent, required=(99.9,) optional={}
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base self=<Image object at 0x7f1f0f1b88c0 (VipsImage at 0xe9fdaaf0)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0f1b88c0 (VipsImage at 0xe9fdaaf0)> to in
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | in needs a <GType VipsImage (33612672)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning <Image object at 0x7f1f0f1b88c0 (VipsImage at 0xe9fdaaf0)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning 99.9 to percent
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | percent needs a <GType gdouble (60)>
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | assigning 99.9
2015-12-08 16:05:27 | gi.overrides.Vips              | DEBUG    | _call_base checking cache for op <__main__.VipsPercent object at 0x7f1f0f1b8910 (VipsPercent at 0xe9e6e980)>
Killed
```

The program was run on a machine with 32GB memory and 8 cores.

The same error occurs when another function is called, e.g. `scale()` instead of `percent()`.

Here is a small test program that illustrates the actual program and might be helpful to reproduce the error:

```python
#! /usr/bin/env python
import os
import numpy as np
import shutil
import tempfile
import itertools
import logging
import argparse
from gi.repository import Vips


def configure_logging():
    logger = logging.getLogger()

    fmt = '%(asctime)s | %(name)-30s | %(levelname)-8s | %(message)s'
    datefmt = '%Y-%m-%d %H:%M:%S'
    formatter = logging.Formatter(fmt=fmt, datefmt=datefmt)

    handler = logging.StreamHandler()
    handler.name = 'stream'
    handler.setFormatter(formatter)
    logger.addHandler(handler)


if __name__ == '__main__':

    configure_logging()

    parser = argparse.ArgumentParser('Test program for Vips pyramid creation.')
    parser.add_argument('-v', '--verbosity', action='count', default=0,
                        help='increase logging verbosity')
    parser.add_argument('-m', '--mosaic_axis_length', default=2, type=int,
                        help='number of images along each dimension of a mosaic')
    parser.add_argument('-o', '--overview_axis_length', default=5, type=int,
                        help='number of mosaics along each dimension of the overview')

    tmp_dir = tempfile.gettempdir()

    args = parser.parse_args()

    logging_level_mapper = {
        0: logging.CRITICAL,
        1: logging.INFO,
        2: logging.DEBUG,
    }

    logger = logging.getLogger('test_vips_pyramid')
    logger.setLevel(logging_level_mapper[args.verbosity])

    vips_logger = logging.getLogger('gi.overrides.Vips')
    vips_logger.setLevel(logging_level_mapper[args.verbosity])

    # Create a squared "overview" image that is composed of many smaller squared
    # "mosaics", each of which is composed of several individual images.
    # NOTE: The size of the actual overview image is at least 0.5 * 10^6 pixels
    # along each dimension.
    mosaic_axis_length = args.mosaic_axis_length
    files = ['file_%d.png' % i for i in range(mosaic_axis_length**2)]

    overview_axis_length = args.overview_axis_length
    folder_names = ['directory_%d' % i for i in range(overview_axis_length**2)]

    input_dir = os.path.join(tmp_dir, 'vips_test', 'inputs')
    if not os.path.exists(input_dir):
        os.makedirs(input_dir)

    output_dir = os.path.join(tmp_dir, 'vips_test', 'outputs')
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)

    directories = [os.path.join(input_dir, f) for f in folder_names]

    # Create images on disk
    # NOTE: The actual images would already exist on disk
    logger.info('create images')
    for d in directories:
        if not os.path.exists(d):
            os.mkdir(d)
        for f in files:
            filename = os.path.join(input_dir, d, f)
            logger.debug('write image to file: %s', filename)
            img = Vips.Image.gaussnoise(100, 100)
           # NOTE: The actual dimensions are 2500 x 2600
            img.write_to_file(filename)

    logger.info('create mosaics')
    moasic_coordinates = list(itertools.product(
                             range(mosaic_axis_length),
                             range(mosaic_axis_length)))
    mosaics = list()
    for i, d in enumerate(directories):
        logger.debug('stitch mosaic # %d', i)
        # Build grid for the current mosaic
        mosaic_grid_dims = (mosaic_axis_length, mosaic_axis_length)
        mosaic_grid = np.empty(mosaic_grid_dims, dtype='O')
        for i, coords in enumerate(moasic_coordinates):
            filename = os.path.join(d, files[i])
            mosaic_grid[coords[0], coords[1]] = filename

        # Load individual images and stitch them together according to the grid layout
        for r in xrange(mosaic_grid.shape[0]):
            for c in xrange(mosaic_grid.shape[1]):

                img = Vips.Image.new_from_file(mosaic_grid[r, c])

                if c == 0:
                    row = img
                else:
                    row = row.merge(img, 'horizontal', -img.width, 0)

            if r == 0:
                mosaic = row
            else:
                mosaic = mosaic.merge(row, 'vertical', 0, -img.height)

        mosaics.append(mosaic)


    logger.info('create overview')
    overview_coordinates = list(itertools.product(
                              range(overview_axis_length),
                              range(overview_axis_length)))
    # Build grid for the final overview image
    overview_grid_dims = (overview_axis_length, overview_axis_length)
    overiew_grid = np.empty(overview_grid_dims, dtype='O')
    for i, coords in enumerate(overview_coordinates):
        overiew_grid[coords[0], coords[1]] = mosaics[i]

    # Create spacer images, which will be inserted between individual mosaics
    img_dtype = img.get_format()
    col_spacer = Vips.Image.black(10, mosaic.height, bands=1).cast(img_dtype)
    row_width = (
        mosaic.width * overview_grid_dims[1] +
        10 * (overview_grid_dims[1] + 1)
    )
    row_spacer = Vips.Image.black(row_width, 10, bands=1).cast(img_dtype)
   
    # Stitch mosaics together according to the grid layout
    overview = row_spacer
    for r in xrange(overiew_grid.shape[0]):
        for c in xrange(overiew_grid.shape[1]):

            if c == 0:
                row = col_spacer

            mosaic = overiew_grid[r, c]
            row = row.join(mosaic, 'horizontal')
            row = row.join(col_spacer, 'horizontal')

        overview = overview.join(row, 'vertical')
        overview = overview.join(row_spacer, 'vertical')

    # Clip intensity values
    logger.info('clip intensities')
    threshold = overview.percent(99.9)
    identity_image = Vips.Image.identity(ushort=True)
    condition_image = (identity_image >= threshold)
    lut = condition_image.ifthenelse(threshold, identity_image)
    overview = overview.maplut(lut)

    # Rescale to 8-bit
    logger.info('rescale intensities')
    overview = overview.scale()

    # Save as pyramid
    logger.info('create pyramid: %s', output_dir)
    overview.dzsave(output_dir, layout='zoomify')
```

Run the program in DEBUG mode:

```bash
test_vips_pyramid.py -vv
```

Vips was installed from git (branch 8.1).

I would like to include @riccardomurri and @smaffiol.

**Comment by HackerMD** [comment]
I should also mention that the program that produced the above provided log output was executed on a compute node of a SLURM cluster. The cluster has a shared network file system with limited disk space. The `input_dir` and `output_dir`, i.e. the directories that contain the PNG image files and the directory were the final pyramid should be stored, are located on an additionally mounted data volume.

The error occurs when the program is submitted as a SLURM job, but also when it is executed on the compute node directly.

**Comment by bgilbert** [comment]
`Killed` often means that the process ran out of memory and was killed by the kernel.  Are there any relevant log messages in `dmesg`?

**Comment by jcupitt** [comment]
@bgilbert is probably right, I think you ran out of memory. 

You're opening PNG images for random access (the default). PNGs do not support random access, so vips has to decompress then to vips format behind your back. Images less than 100mb are decompressed to ram, so your tiles are all being kept in memory.

I think I would open in sequential mode, then vips will stream your PNGs directly from libpng to the output. Add `access = Vips.Access.SEQUENTIAL` to the `.new_from_file()`. 

This should fix the memory issue, but you'll have two new problems. First, the program will try to keep 10,000 files open at once, which may be too much. You can try adjusting your `ulimit`, it might let you go up to 10,000, I think it depends how your system has been configured. Alternatively, you'll have to build your image in 1,000 tile chunks. 

Your second problem would be the `.scale()`. This scans the whole input image to find min and max, and then calculates a scale and offset and writes the output. This will result in two scans of every tile, and won't work in sequential mode. You'll need to have a fixed scale and offset, or perhaps just take the top 8 bits.

**Comment by jcupitt** [comment]
Sorry, I read your code too quickly. I wouldn't use `.merge()` unless you really need feathered edges on the joins, just use `.join()`. I'm not sure merge will work in seq mode. 

`.join()` supports spacers:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-join

Use something like `shim = 10`. 

For the scale, I think you'll need to do two passes: one to join, find the histogram and calculate a lut, and a second pass to join, process and save. It'll be rather slow :-(

**Comment by HackerMD** [comment]
Thank you @jcupitt and @bgilbert for your immediate feedback!

Do you think it would work if we would break the problem down into smaller subproblems?

In a first step, each "mosaic" could be created independently and scaled using fixed values, which could be pre-calculated by sampling only a few images. The resulting `Vips.Image` objects could then be temporary stored on disk in a format that supports random access.

In a second step, the "mosaics" could be read from disk and stitched together to the final "overview" and saved using `dzsave()`.

I would in principle also have the option to store images in a format other than PNG. The reason why I chose PNG is because it's supports lossless compression of 16bit images and the files can be read with standard readers by almost any library. I already experimented with HDF5. It would allow random access. Which would be your format of choice?

**Comment by HackerMD** [comment]
> I wouldn't use .merge() unless you really need feathered edges on the joins

I use `merge()` in order to be able to account for a potential overlap between images. But I could also omit this for now.

I was also thinking of "preallocating" a black `Vips.Image` object and then `insert()` individual images according to the grid layout. I know dimensions in advance and all images have the same dimensions. Would this be an alternative to `join()`?

**Comment by HackerMD** [comment]
> Use something like shim = 10.

Thanks for the hint! I missed that parameter.

**Comment by jcupitt** [comment]
Yes, black + insert is a simple alternative, it'd execute at the same speed, so pick whichever seems neater.

You can do all of load PNGs + assemble + dzsave in a single step. I think I'd try a test run assembling all 10,000 just to get an idea of runtime and what you need to do to be able to open 10,000 files at the same time. 

If it works, then try running in two stages: first, assemble and find a histogram, second assemble again but this time map and save. As you say, you could try just analyzing a couple of the images for the threshold, that would save a lot of time. 

I usually use TIFF. It's fast and flexible (too flexible). PNG is extremely slow, unfortunately, I'm not sure why.

```
$ time vips copy wtc.jpg x.png
real	0m28.417s
user	0m29.056s
sys	0m0.148s
$ time vips copy wtc.jpg x.tif[compression=deflate,predictor=horizontal]
real	0m19.536s
user	0m20.088s
sys	0m0.148s
$ ls -l x.tif x.png
-rw-rw-r-- 1 john john 135811739 Dec  8 19:53 x.png
-rw-rw-r-- 1 john john 143610716 Dec  8 19:54 x.tif
```

The PNG is marginally smaller, but takes 50% longer to read or write. TIFF has a tiled mode too, which supports efficient random access. Or of course you can just use uncompressed files, provided you have enough disk space. 

```
$ time vips copy wtc.jpg x.png[compression=0]
real	0m6.110s
user	0m6.592s
sys	0m0.212s
$ time vips copy wtc.jpg x.tif
real	0m0.787s
user	0m0.808s
sys	0m0.276s
$ ls -l x.png x.tif
-rw-rw-r-- 1 john john 263942037 Dec  8 20:00 x.png
-rw-rw-r-- 1 john john 263507122 Dec  8 19:59 x.tif
```

Though PNG is even slow at reading and writing uncompressed data. Uncompressed PNG is slower than JPG, despite not really needing to do anything.

**Comment by HackerMD** [comment]
I've adapted the code according to your recommendations:
- `join()` instead of `merge()` (using `shim` instead of spacer)
- `Vips.Image.new_from_file()` with `access=Vips.Access.SEQUENTIAL`
- replace `scale()` by manual rescaling with pre-calculated values

```python
#! /usr/bin/env python
import os
import numpy as np
import shutil
import tempfile
import itertools
import logging
import argparse
from gi.repository import Vips


def configure_logging():
    logger = logging.getLogger()

    fmt = '%(asctime)s | %(name)-30s | %(levelname)-8s | %(message)s'
    datefmt = '%Y-%m-%d %H:%M:%S'
    formatter = logging.Formatter(fmt=fmt, datefmt=datefmt)

    handler = logging.StreamHandler()
    handler.name = 'stream'
    handler.setFormatter(formatter)
    logger.addHandler(handler)


if __name__ == '__main__':

    configure_logging()

    parser = argparse.ArgumentParser('Test program for Vips pyramid creation.')
    parser.add_argument('-v', '--verbosity', action='count', default=0,
                        help='increase logging verbosity')
    parser.add_argument('-m', '--mosaic_axis_length', default=2, type=int,
                        help='number of images along each dimension of a mosaic')
    parser.add_argument('-o', '--overview_axis_length', default=5, type=int,
                        help='number of mosaics along each dimension of the overview')

    tmp_dir = tempfile.gettempdir()

    args = parser.parse_args()

    logging_level_mapper = {
        0: logging.CRITICAL,
        1: logging.INFO,
        2: logging.DEBUG,
    }

    logger = logging.getLogger('test_vips_pyramid')
    logger.setLevel(logging_level_mapper[args.verbosity])

    vips_logger = logging.getLogger('gi.overrides.Vips')
    vips_logger.setLevel(logging.CRITICAL)

    # Create a squared "overview" image that is composed of many smaller squared
    # "mosaics", each of which is composed of several individual images.
    mosaic_axis_length = args.mosaic_axis_length
    files = ['file_%d.png' % i for i in range(mosaic_axis_length**2)]

    overview_axis_length = args.overview_axis_length
    folder_names = ['directory_%d' % i for i in range(overview_axis_length**2)]

    input_dir = os.path.join(tmp_dir, 'vips_test', 'inputs')
    if os.path.exists(input_dir):
        shutil.rmtree(input_dir)
    os.makedirs(input_dir)

    output_dir = os.path.join(tmp_dir, 'vips_test', 'outputs')
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)

    directories = [os.path.join(input_dir, f) for f in folder_names]

    # Create images on disk
    logger.info('create images')
    for d in directories:
        if not os.path.exists(d):
            os.mkdir(d)
        for f in files:
            filename = os.path.join(input_dir, d, f)
            logger.debug('write image to file: %s', filename)
            img = Vips.Image.gaussnoise(100, 100)
            img.write_to_file(filename)

    logger.info('create mosaics')
    moasic_coordinates = list(itertools.product(
                             range(mosaic_axis_length),
                             range(mosaic_axis_length)))
    mosaics = list()
    for i, d in enumerate(directories):
        logger.debug('stitch mosaic # %d', i)
        # Build grid for the current subpart of the final overview image
        mosaic_grid_dims = (mosaic_axis_length, mosaic_axis_length)
        mosaic_grid = np.empty(mosaic_grid_dims, dtype='O')
        for i, coords in enumerate(moasic_coordinates):
            filename = os.path.join(d, files[i])
            mosaic_grid[coords[0], coords[1]] = filename

        # Load individual images and stitch them together
        for r in xrange(mosaic_grid.shape[0]):
            for c in xrange(mosaic_grid.shape[1]):

                img = Vips.Image.new_from_file(
                            mosaic_grid[r, c],
                            access=Vips.Access.SEQUENTIAL)

                if c == 0:
                    row = img
                else:
                    row = row.join(img, 'horizontal', shim=0)

            if r == 0:
                mosaic = row
            else:
                mosaic = mosaic.join(row, 'vertical', shim=0)

        mosaics.append(mosaic)

    # Stitch mosaics together
    logger.info('create overview')
    overview_coordinates = list(itertools.product(
                              range(overview_axis_length),
                              range(overview_axis_length)))
    # Build grid for the final overview image
    overview_grid_dims = (overview_axis_length, overview_axis_length)
    overiew_grid = np.empty(overview_grid_dims, dtype='O')
    for i, coords in enumerate(overview_coordinates):
        overiew_grid[coords[0], coords[1]] = mosaics[i]

    # Create spacer images, which will be inserted between individual mosaics
    space = 10
    dtype = img.get_format()
    col_spacer = Vips.Image.black(space, mosaic.height, bands=1).cast(dtype)
    row_width = (
        mosaic.width * overview_grid_dims[1] +
        space * (overview_grid_dims[1] + 1)
    )
    row_spacer = Vips.Image.black(row_width, space, bands=1).cast(dtype)

    overview = row_spacer
    for r in xrange(overiew_grid.shape[0]):
        for c in xrange(overiew_grid.shape[1]):

            if c == 0:
                row = col_spacer

            mosaic = overiew_grid[r, c]
            row = row.join(mosaic, 'horizontal', shim=space)

        overview = overview.join(row, 'vertical', shim=space)

    overview.join(row_spacer, 'vertical')

    # Rescale overview image to 8-bit
    logger.info('rescale intensities')
    # For now, let's simply use a fixed value
    max_value = 2**12
    overview = (overview.cast('float') / max_value * 255).cast('uchar')

    # Save overview image as pyramid on disk
    logger.info('create pyramid: %s', output_dir)
    overview.dzsave(output_dir, layout='zoomify')
```

This approach works with 6561 images:

```bash
test_vips_pyramid.py -vv -m 9 -o 9
```

But with 10000 images there are problems:

```bash
test_vips_pyramid.py -vv -m 10 -o 10
```

The `dzsave()` method seems to get's stuck. It takes forever, without any new JPEG files appearing in the output folder.

If PNG represents such a bottleneck I will switch to TIFF format. We will have to sacrifice some disk space, but will gain performance and hopefully also solve this issue.

I have re-submitted jobs. We'll know in a few hours..

Thank you very much for your support!

**Comment by jcupitt** [comment]
I think you're seeing a stack overflow, your pipeline is just too long :-( libvips recurses down pipes to work out which pixels to calculate next, and this puts a limit on maximum pipeline length. 

You can rearrange your joins to reduce the max length. At the moment you do 10 joins on each smallest axis, with an image on one side of the join and the rest of the row on the other -- this means you are getting a pipe 10 nodes deep. 

You can reorder this to have the two sides be pipes of equal length. First join each pair of images, so 0 to 1, 2 to 3, 4 to 5, and so on, then join those pairs up, so (0+1) joins (2+3), (4+5) joins (6+7), etc., then finally join those bits. You'll get a pipe 4 nodes deep instead. 

Does that make sense? It's the difference between 

(0+(1+(2+(3+(4+(5+(6+(7+(8+9))))))))) 

and 

(((0+1)+(2+3))+((4+5)+(6+7)))+(8+9)

You can do the same trick on all the vertical joins too, of course.

**Comment by jcupitt** [comment]
I meant to say, I tried here with TIFF and see strange crashes with higher sizes too. Looks like a C stack overflow.

**Comment by HackerMD** [comment]
The jobs with the TIFF files are still running..

> You can rearrange your joins to reduce the max length.

I'll try this approach! Thanks!

What effect would the `insert()` approach (first preallocating a large black image and then inserting individual images into it) have on pipeline length?

**Comment by HackerMD** [comment]
I just go the first job result - it also failed with TIFF.

Will now try both approaches:
- pair-wise `join()`
- `insert()`

**Comment by jcupitt** [comment]
black + insert wouldn't make any difference, I think.

**Comment by jcupitt** [comment]
I tried this:

```python
def join_list(image_list, direction, shim = 0):
    while len(image_list) > 1:
        image_list = [image_list[i].join(image_list[i + 1], direction, shim = shim)
                      for i in range(0, len(image_list) - 1, 2)]
    return image_list[0]
```

To join a list of images up with a smaller pipe depth. I can do one deeper now, but not more. 

I'll try to think about this again. You might need to join up the mosaics and write to TIFFs, then join those TIFFs again to make your overview.

**Comment by HackerMD** [comment]
Thanks! I've implemented it similarly using `join()` together with `reduce()`. Jobs are running. Let's see..

However, even if this approach works for the current dataset, it may ultimately represent a bottleneck. Since I would like to create even larger overviews, we may have to come up with an approach that scales better.

> You might need to join up the mosaics and write to TIFFs, then join those TIFFs again to make your overview.

This approach would be straight forward to implement and the first step could be parallelised. The only thing I'm worried about is disk space. Would the TIFF files need to persist as long as the program would run, i.e. also while `dzsave()` would be creating the pyramid tiles? This would mean that we would have several copies of a large dataset. This may represent another bottleneck, since we would need terabytes of extra disk space, since we would process several of these datasets in parallel.

An alternative approach would be to stitch the mosaics via `numpy` and convert them to `Vips.Image` objects in memory using  `new_from_memory_copy()`. Do you think this would work with such large arrays? I haven't tested it yet, since I first need to install the master branch again (I'm still working with 8.1, see [issue #346](https://github.com/jcupitt/libvips/issues/346)).

**Comment by HackerMD** [comment]
I recently also had a discussion with colleagues about parallelising the process on a cluster over nodes (in addition to the parallelisation over CPUs that's done by Vips). Thereby, we could reduce the memory requirements for a single machine. We would probably also gain in terms of performance because we could perform I/O in parallel rather than having to load each image sequentially. From my point of view the major issue would be the creation of the pyramid tiles à la `dzsave()` without having the whole overview image available on one machine. We briefly discussed the option of using MPI. Do you think this would in principle be possibly with Vips?

**Comment by HackerMD** [comment]
Unfortunately, the "pair-wise" `join()` approach also failed.

**Comment by jcupitt** [comment]
I thought of a further small improvement to `.join()`. This change makes it use a little less stack:

https://github.com/jcupitt/libvips/commit/a649ae111d88c93b3bef72cbb873c730623944d3

But I still can't do 8 x 8 on this laptop. I think the fix will be to add a special join-array operator, I'll have a go.

Disk intermediates: yes, there would need to be a second copy of the input images. 

I don't think using numpy would help, I think you need more image at once than you have memory, so numpy won't work.

I'm not sure about MPI. There's an experimental branch of vips that can load formats like tiff from a socket, perhaps you could use that to link several machines together? It would need a bit of work though.

I think the simplest solution is probably to add a join-array operator. Give me a day or two.

**Comment by HackerMD** [comment]
> I think the simplest solution is probably to add a join-array operator. 

That would be great!

> There's an experimental branch of vips that can load formats like tiff from a socket, perhaps you could use that to link several machines together? It would need a bit of work though.

Maybe I can find a motivated colleague who'd be willing to work on this :)

**Comment by jcupitt** [comment]
The branch is here:

https://github.com/jcupitt/libvips/blob/load-from-stream

But looking at it again it has some severe problems, it would not be an easy thing to fix up.

**Comment by jcupitt** [comment]
I added vips_arrayjoin(), your program seems to work fine now:

https://gist.github.com/jcupitt/86197925f7e0b38a08d5

It's your code with the smallest possible number of changes, so it badly needs some reworking for the new operator. It should be able to handle very, very large arrays. 

The new function is here:

https://github.com/jcupitt/libvips/blob/master/libvips/conversion/arrayjoin.c#L427

See the comments for usage.

**Comment by HackerMD** [comment]
Thank you very much for implementing the new function!
I've tested it and it works.

It seems to require more memory, however.
Using the `vips_arrayjoin()` approach, jobs are now getting killed already upon overview creation (within the outer loop that appends the list of mosaics).
But at least the error message is more specific now :)

```bash
slurmd[compute002]: Job 272135 exceeded 30720000 KB memory limit, being killed
slurmd[compute002]: Exceeded job memory limit
```

I'm now trying a combined approach:
- `vips_arrayjoin()` for creation of individual mosaics (inner joins)
- `join()` for the creation of the overview, i.e. stitching the mosaics together (outer joins)

I've tested this combination on a smaller dataset and it reduced memory requirements by about 15%.

Images are created form files using `SEQUENTIAL_UNBUFFERED` access.

**Comment by jcupitt** [comment]
I've been digging a bit and it seems most of the high memory use is down to the tiff reader. It just doesn't scale well to 10,000 simultaneous read operations active at once. 

If I change the intermediate format to vips, eg.:

```python
    files = ['file_%d.v' % i for i in range(mosaic_axis_length**2)]
```

I see:


```
$ time ./markus.py -m 10 -o 10
memory: high-water mark 11.84 MB
real	2m27.101s
user	2m34.104s
sys	3m41.024s
```

So tiny memory use and much faster. I don't suppose you could switch to vips format? ppm would probably work as well, that can read efficiently.

**Comment by HackerMD** [comment]
Mmh.. I would rather avoid switching to Vips format, since most other libraries (ImageJ, OpenCV, ...) are not able to read this format and there are also programming languages for which no Vips interfaces are available.

But I will nevertheless give it a test to see whether this would solve the problem.

PPM could be an option. However, it seems that PPM doesn't support compression!? Since I have a lot of images storage matters.

What about HDF5? This format has generally very good performance and supports random access. I'm using HDF5 for basically all non-image data via [h5py](http://docs.h5py.org/en/latest/) and [pytables](http://www.pytables.org/). I've been experimenting with reading and writing compressed images via h5py and achieved compression levels similar to TIFF and PNG (GZIP filter).

```python
import cv2
import h5py

img = cv2.imread('test.tiff', cv2.IMREAD_UNCHANGED)
img[1, 2]
f = h5py.File('test.h5', 'w')
f.create_dataset("image_compressed", data=img, compression="gzip")
f.close()

f = h5py.File('test.h5', 'r')
f['image_compressed'][1, 2]
f.close()
```

Vips in principle supports HDF5 files via *matio*, since the newer v7.3 Matlab files are HDF5 files.

I've tested the following on my Mac:

```
brew install libmatio --with-hdf5
brew install vips --with-libmatio
```

Load an image in Matlab and save it as a *.mat* file:

```matlab
image_filen = 'test.tiff';
image = uint16(imread(image_file));
image(2, 3)

save(fullfile(directory, 'test.mat'), 'image', '-v7.3')
```

The resulting *.mat* file is an HDF5 file:

```
$ h5ls test.mat
image                    Dataset {2560/Inf, 2160/Inf}   # Matlab inverts the image
```

I can load the image via Vips in Python and get the correct values:

```python
from gi.repository import Vips

img = Vips.Image.matload('test.mat')
img.avg()
img(1, 2)
```

This doesn't work using *h5py* in Python:

```python
import cv2
import h5py

img = cv2.imread('test.tiff', cv2.IMREAD_UNCHANGED)

f = h5py.File('test2.mat', 'w')
f.create_dataset('image', data=img)  # without compression
f.close()
```

```
$ h5ls test2.mat
image                    Dataset {2160, 2560}
```

```python
from gi.repository import Vips

img = Vips.Image.matload('test2.mat')
```

```python
<ipython-input-11-602e2dbbf369> in <module>()
----> 1 Vips.Image.matload('test2.mat')

/Users/mdh/Envs/tmlibrary/lib/python2.7/site-packages/gi/overrides/Vips.pyc in class_method(cls, *args, **kwargs)
   1031     @add_doc(generate_docstring(name))
   1032     def class_method(cls, *args, **kwargs):
-> 1033         return _call_base(name, args, kwargs)
   1034 
   1035     return class_method

/Users/mdh/Envs/tmlibrary/lib/python2.7/site-packages/gi/overrides/Vips.pyc in _call_base(name, required, optional, self, option_string)
    336     logging.debug('_call_base got op2 %s' % op2)
    337     if op2 == None:
--> 338         raise Error('Error calling operator %s.' % name)
    339 
    340     # rescan args if op2 is different from op

Error: Error calling operator matload.
  mat2vips: unable to open "test2.mat"
```

HDF5 may also not be the optimal image file format, but it has interfaces for almost all languages. Do you see a way to support reading and writing HDF5 files in Vips?

**Comment by HackerMD** [comment]
Reading images from Vips format via `Vips.Image.new_from_file(filename, access=Vips.Access.SEQUENTIAL_UNBUFFERED)` gives me the following error after reading a couple of hundreds of files:

```
No known loader for "/data/storage/testdata/images/0_t000_D07_y001_x000_c000_z000.v".
  vips__file_open_read: unable to open file "/data/storage/testdata/images/0_t000_D07_y001_x000_c000_z000.v" for r
eading
unix error: Too many open files
VipsForeignLoad: "/data/storage/testdata/images/0_t000_D07_y001_x000_c000_z000.v" is not a known file format
```

Of note, the approach works on a smaller test dataset.

I'm retrying with default `Vips.Image.new_from_file(filename)`.

**Comment by HackerMD** [comment]
Same error with `Vips.Image.new_from_file(filename)`.

**Comment by jcupitt** [comment]
I think that's an easy one:

```
unix error: Too many open files
```

You need `ulimit -n 15000` to raise the max number of open files.

**Comment by jcupitt** [comment]
The reason vips and ppm would work is that they are not really file formats, they are just arrays dumped to disk with a little metadata. So vips doesn't need to decode them, it can just map bits of the files into memory and use them directly. Since there's no input buffer, memory requirements are very low.

I think HDF5 would have the same problem as TIFF. You'd need a decode library and a buffer to decode to, which is fine for a small number of files open at once, but which will be difficult for 10,000 files active at the same time. 

I had another thought overnight, I'll see if I can get the memuse with tiff down a bit.

**Comment by HackerMD** [comment]
> I'll see if I can get the memuse with tiff down a bit

Great! Thanks!

> I think HDF5 would have the same problem as TIFF. You'd need a decode library and a buffer to decode to, which is fine for a small number of files open at once, but which will be difficult for 10,000 files active at the same time.

With HDF5 we could group several images per file, or even have all images in a single file.

I the meantime, I will retry raising `ulimit`.

**Comment by jcupitt** [comment]
I found a couple of bugs! Try again with git master, I now see:

```
$ time ./markus.py -m 10 -o 10
memory: high-water mark 590.10 MB
real	2m24.877s
user	3m6.600s
sys	5m27.868s
```

Down from 5m, 2GB. 

There were two problems. First, the tiff loader was trying to hint that it could produce strips of pixels (the fast way to read sequentially from tiff files), but the hint wasn't making it downstream. This resulted in the `dzsave` operation working on 128 x 128 tiles instead, which resulted in vips having to keep 128 lines from each of the 10,000 source images. It's now actually doing strip-based processing and it's much quicker and needs a lot less memory. 

You could also experiment with reducing the rows per strip setting. vips reads tiff files a strip at a time, and if your rowsperstrip is high, this can mean large input buffers. Try:

```
$ tiffinfo wtc.tif | grep Rows
  Rows/Strip: 128
```

See if you can get that number down. I don't know how you're making your tiffs, but vips lets you set the rowsperstrip like this:

```
$ vips copy wtc.jpg wtc.tif[tile_height=8]
$ tiffinfo wtc.tif | grep Rows
  Rows/Strip: 8
```

Or in your test program, change the writer to be:

```
        for f in files:
            filename = os.path.join(input_dir, d, f)
            logger.debug('write image to file: %s', filename)
            img = Vips.Image.gaussnoise(100, 100)
            img.write_to_file(filename, tile_height = 8)
```

ie. add a `tile_height` option.

It won't make much difference with the tiny images in your test, but it could drop memuse when you try the large images.

Secondly, I found that `DEBUG` had been left on in `buffer.c` and this was causing a huge amount of unnecessary extra locking and list manipulation. How annoying! There's now a thing to warn if `DEBUG` is enabled there.

**Comment by HackerMD** [comment]
In the meanwhile, we've rebuild the cluster and added 128GB nodes with 32 cores. On these machines the program now progressed to the `dzsave()` step and part of the pyramid got written to disk. But after at about 20% of tiles, the job got killed again.

The TIFFs were generated using OpenCV's `imwrite()` function and `tiffinfo` says:

```
Rows/Strip: 1
```

**Comment by jcupitt** [comment]
Have you tried with the latest git master vips? I think it'll work now, or it should do. Does it run cleanly on your desktop machine?

**Comment by HackerMD** [comment]
It should be the latest git master vips:

```
tmaps@frontend001:~/libvips_source$ git log
commit 7c506b4351285abac9f50ba2590b472a8b07ce2f
Author: John Cupitt <jcupitt@gmail.com>
Date:   Mon Dec 14 14:08:45 2015 +0000

    stupid gtk-doc
```

Currently, I cannot run it on my Desktop machine, because I haven't managed to install it from source on OSX.

**Comment by jcupitt** [comment]
Could you maybe run that test python program on the cluster and confirm you see the same memory behaviour I see here?

Latest version of the test program:

**Comment by jcupitt** [comment]
... I just noticed you are making 100 x 100 pixel float tiffs. If I change it to uchar, I see:

```
$ time ./markus.py -vv -m 10 -o 10
memory: high-water mark 187.75 MB

real	2m25.606s
user	3m17.584s
sys	5m12.724s
```

I'll try experimenting with larger images to see how memuse scales. How large are your images on the cluster? 3000 x 3000 8-bit?

**Comment by HackerMD** [comment]
My images have the following dimensions and bit depth:  2160 x 2560 16-bit.

The `time ./markus.py -m 10 -o 10` test is still running. Takes forever..
Could this all be related to NFS?

**Comment by HackerMD** [comment]
I mean not only the longer reading/writing time, but also the higher memuse?

**Comment by jcupitt** [comment]
Oh crumbs, NFS? I hadn't taken that in. 

It'll certainly be very slow, I don't know about memory use, you'd need to ask an expert. I imagine 10,000 files open at once in a single process could cause some problems. 

There's little actual processing going on here, your application is disk IO bound, it'll go as fast as your disks go. You don't need much CPU, or even that much memory now that vips is being less stupid, you just need huge amounts of disk bandwidth, as much as you can get. 

Could you maybe add a couple of TB of local disk as working storage? You could consider using several drives and raid or zfs.

**Comment by jcupitt** [comment]
I guess these are mono images? That's about 11MB per image uncompressed, so only 110GB for all your source images. You can put them on an SSD for less than $50, that might be the cheapest way to do it. 

I'll try scaling the test program up slowly with mono ushort pixels and see what happens to memuse.

**Comment by HackerMD** [comment]
The test failed:

```
tmaps@fat:~$ time ./markus.py -vv -m 10 -o 10
....
2015-12-16 14:05:02 | test_vips_pyramid              | INFO     | create pyramid: /home/tmaps/tmp/pics/vips_test/outputs
**
VIPS:ERROR:region.c:887:vips_region_fill: assertion failed: (reg->im->generate_fn)
Aborted (core dumped)

real	51m45.519s
user	6m52.221s
sys	1m44.452s
```

I used the code the [markus.py](https://gist.github.com/jcupitt/86197925f7e0b38a08d5) code and only changed the `tmp_dir` variable.

**Comment by HackerMD** [comment]
> so only 110GB for all your source images

True, but I have several hundreds of these datasets (and bigger ones) and they have to be processed in parallel.

**Comment by jcupitt** [comment]
Did you remember the ulimit? It can coredump if it runs out of file descriptors. I ought to fix that :( 

I've only tried 100 x 100, 150 x 150 and 200 x 200 so far, but it memuse looks roughly linear:

![x](https://cloud.githubusercontent.com/assets/580843/11843826/87473e6e-a403-11e5-98a6-98c122248232.png)

So for 2160 pixels across it should need about 15gb of ram. I'll add a couple more data points.

**Comment by HackerMD** [comment]
It's weird!

```
tmaps@fat:~$ ulimit -n
1024
```

Running the same code with another data resource (the mounted share that I also use for the actual processing) speeds things up dramatically:

```
tmaps@fat:~$ time ./markus.py -vv -m 10 -o 10
....
5-12-16 14:42:20 | test_vips_pyramid              | INFO     | create pyramid: /data_tmaps/storage/vips_test/outputs
**
VIPS:ERROR:region.c:887:vips_region_fill: assertion failed: (reg->im->generate_fn)
Aborted (core dumped)

real	4m19.722s
user	6m44.526s
sys	1m18.899s
```

**Comment by jcupitt** [comment]
You need to raise `ulimit`, try:

```
ulimit -n 15000
```

It sets the maximum number of files open at once. You need at least 10,000 for this program. 

The speedup is very odd, ah well, NFS. I'm glad it's crashing more quickly at least  :)

**Comment by jcupitt** [comment]
I added an other data point, it seems to continue roughly linearly.

![x](https://cloud.githubusercontent.com/assets/580843/11844250/9feeea32-a405-11e5-8c85-c8114c41f356.png)

**Comment by HackerMD** [comment]
Took me a while to figure out how to increase the number of open files because `ulimit -n 15000` didn't work.

But now it's:

```
tmaps@fat:~$ ulimit -n
1048576
```

With this the test ran successfully:

```
memory: high-water mark 925.83 MB

real	1m38.956s
user	1m45.330s
sys	1m13.321s
```

Here I didn't recreate the files again, but used the ones that were created previously to make things fail even faster :)

**Comment by HackerMD** [comment]
Now, I'll give the actual dataset another shot..

**Comment by jcupitt** [comment]
Yes, how well `ulimit` works depends a bit on your linux, unfortunately. Until a few years ago it was impossible to go over 1024 unless you recompiled your kernel.

**Comment by HackerMD** [comment]
Also the increase in `ulimit` didn't solve the problem. Jobs are still killed.

What I should maybe mention is that I get the following warning message for each individual image when upon loading and tiling:
```
vips warning: tiff2vips: no resolution information for TIFF image
```

**Comment by jcupitt** [comment]
That warning should be harmless. I hope. 

On the test, you are seeing memuse of 920MB to my 590MB, so it looks like your scale factor is higher. Perhaps with the full set you are going over 32GB, or whatever your limit is.

Could the difference be how many hardware threads are available? vips memuse generally scales with image width and with number of threads. I have 12 on my desktop (six hyperthreaded cores), if you have double that, it could maybe almost double memory use. 

This application is IO bound rather than CPU bound, so the extra threads are probably not doing much. I would try setting `VIPS_CONCURRENCY` to some small number. This environment variable sets the size of the vips worker pool. For example (on my laptop):

```
$ ulimit -n 15000
$ time ./markus.py -m 10 -o 10
memory: high-water mark 456.94 MB
real	2m33.825s
user	2m50.500s
sys	3m41.148s
$ export VIPS_CONCURRENCY=1
$ time ./markus.py -m 10 -o 10
memory: high-water mark 179.04 MB
real	1m9.572s
user	1m10.152s
sys	0m4.660s
```

It's actually a lot quicker with threading off, amusingly, sigh. 

You could also double-check that the changes we made to the test program are in your full application. So: use of `arrayjoin()` and use of `SEQUENTIAL_UNBUFFERED`.

You could also try running with a smaller dataset, perhaps just a single 10 x 10 join, and check memuse for that case.

**Comment by jcupitt** [comment]
On OS X build, install vips via homebrew to bring in all the packages you need, then use this configure line:

```
CFLAGS="-O3" CXXFLAGS="-O3" ./configure --prefix=/Users/john/vips --with-jpeg-includes=/usr/local/opt/jpeg-turbo/include --with-jpeg-libraries=/usr/local/opt/jpeg-turbo/lib --without-magick
```

There's a problem with the latest imagemagick, and you need to point it at jpeg-turbo.

**Comment by HackerMD** [comment]
Thanks for the hint for the configuration. I can successfully build with this command, but unfortunately, the Python bindings via overwrites are not build.

```
configure: WARNING: pygobject-3.0 not found; disabling vips8 python support
```

I install `pygobject3` via homebrew.

It's located at `/usr/local/include/pygobject-3.0`.

So I tried setting `PYGOBJECT_LIBS` and `PYGOBJECT_CFLAGS` but without success.

**Comment by jcupitt** [comment]
I guess you have `gobject-introspection` installed?

**Comment by HackerMD** [comment]
Yes!

```
[mdh:~/libvips]$ brew install gobject-introspection                                                                                     (master✱) 
Warning: gobject-introspection-1.44.0 already installed
```

I also get the Python bindings when I install Vips via homebrew.

But I also see

```
checking for gobject-introspection... no
```

**Comment by HackerMD** [comment]
Btw.. I resubmitted jobs on the cluster using `.ppm` files. Together with the increased `ulimit` this does pretty well so far. It's still running and I've already accumulated quite a lot of TileGroups :) Fingers crossed!

**Comment by jcupitt** [comment]
I tried reinstalling everything on my Mac, I've made notes here:

http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_OS_X#From_GIT_on_OS_X

I think (maybe?) you forgot to set `PKG_CONFIG_PATH`. It's worth trying anyway.

**Comment by jcupitt** [comment]
OK, all this work is in 8.2, the new version. Please reopen if there are still problems.

**Comment by HackerMD** [comment]
In the meanwhile, I've developed a cluster-based solution to build pyramids in batch mode. Images do not have to be pre-loaded anymore, but pixels are directly mapped to tiles. Thereby, I only need to load a few images at a time, which keeps memory requirements to a minimum, and can now create pyramids of unlimited size. For smaller pyramids, I stick to Vips approach with the latest improvements. Thank you very much for your efforts!
